### ISSUE TITLE
create_pointloads_vtk.py: not running (numElem)

### ISSUE THREAD

**Issue by mlp6** [mlp6/fem#10]
```
Extracting data . . .
Writing node positions
Traceback (most recent call last):
  File "/home/mlp6/projects/fem/mesh/create_pointloads_vtk.py", line 430, in <module>
    main()
  File "/home/mlp6/projects/fem/mesh/create_pointloads_vtk.py", line 56, in main
    create_vtu(args)
  File "/home/mlp6/projects/fem/mesh/create_pointloads_vtk.py", line 136, in create_vtu
    numNodes, numElems = writeNodePositions(loadout, args, 'vtu')
  File "/home/mlp6/projects/fem/mesh/create_pointloads_vtk.py", line 237, in writeNodePositions
    if args.numElem[0] is None:
AttributeError: 'Namespace' object has no attribute 'numElem'
```

**Comment by mlp6** [comment]
* move this to be a method of the `Pointloads` class

* leverage `pyevtk` or `post/SaveVTK` to do this instead of a stand-along script/module
