### ISSUE TITLE
tukey_gauss_qsym_pml example does not work but gauss_qsym_pml not

### ISSUE THREAD

**Issue by AnnaEKnight** [mlp6/fem#90]
unclear if this is a python3.8 issue or if the tukey example is a dead end that should be removed.

**Comment by AnnaEKnight** [comment]
(.venv) aek27@dcc-login-03  /work/aek27/TestingFemTools2021/QsymTry1 $ cat slurm-3390753.out 

INFO:fem.mesh.GenMesh:872176/872176 nodes written to nodes.dyn

INFO:fem.mesh.GenMesh:843750/843750 elements written to elems.dyn

STARTED: Thu Feb 25 14:40:51 2021

HOST: dcc-ultrasound-01

Traceback (most recent call last):

  File "/var/spool/slurmd/job3390753/slurm_script", line 36, in <module>

    generate_loads([0.1, 0.1, 0.75], [0.0, 0.0, -1.5], tukey_length=2.5)

  File "/work/aek27/.venv/lib/python3.8/site-packages/fem/mesh/GaussExc.py", line 42, in generate_loads

    load_nodeID_amp = read_process_nodes(sigma, center, sym, amp, amp_cut,

  File "/work/aek27/.venv/lib/python3.8/site-packages/fem/mesh/GaussExc.py", line 80, in read_process_nodes

    nodeGaussAmp = calc_tukey_amp(fields, center, sigma,

  File "/work/aek27/.venv/lib/python3.8/site-packages/fem/mesh/GaussExc.py", line 249, in calc_tukey_amp

    z_scale = tukey_z_scale(node_xyz[3], center[2], tukey_length, tukey_alpha)

  File "/work/aek27/.venv/lib/python3.8/site-packages/fem/mesh/GaussExc.py", line 276, in tukey_z_scale

    from scipy.signal import tukey

  File "/work/aek27/.venv/lib/python3.8/site-packages/scipy/__init__.py", line 141, in <module>

    from scipy._lib._ccallback import LowLevelCallable

  File "/work/aek27/.venv/lib/python3.8/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>

    from . import _ccallback_c

  File "_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c

  File "/opt/apps/rhel7/python-3.8.1/lib/python3.8/ctypes/__init__.py", line 7, in <module>

    from _ctypes import Union, Structure, Array

ImportError: libffi.so.7: cannot open shared object file: No such file or directory

**Comment by mlp6** [comment]
The unit test is passing just fine: https://github.com/mlp6/fem/blob/main/tests/test_GaussExc.py

**Comment by mlp6** [comment]
Doesn't appear to be a bug; might be an issue with activating the venv.
